// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    FlowButton: typeof import('flowbite-vue')['Button']
    FlowDropdown: typeof import('flowbite-vue')['Dropdown']
    FlowListGroup: typeof import('flowbite-vue')['ListGroup']
    FlowListGroupItem: typeof import('flowbite-vue')['ListGroupItem']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    Posts: typeof import('./src/components/Posts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toasts: typeof import('./src/components/Toasts.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
  }
}
